### ISSUE TITLE
Ошибка опроса состояния порта

### ISSUE THREAD

**Issue by drblez** [Pshatsillo/openHABMegaDevice#3]
```
2016-09-03 15:01:53.201 [INFO ] [b.m.internal.MegaDeviceBinding] - http://192.168.40.43/sec/?pt=2&cmd=get
2016-09-03 15:01:53.208 [INFO ] [b.m.internal.MegaDeviceBinding] - input string->OFF/0
2016-09-03 15:01:53.212 [ERROR] [.service.AbstractActiveService] - Error while executing background thread MegaDevice Refresh Service
java.lang.ArrayIndexOutOfBoundsException: 1
    at org.openhab.binding.megadevice.internal.MegaDeviceBinding.ScanPortsScheduler(MegaDeviceBinding.java:273) ~[na:na]
    at org.openhab.binding.megadevice.internal.MegaDeviceBinding.execute(MegaDeviceBinding.java:182) ~[na:na]
    at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
    at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
```

**Comment by Pshatsillo** [comment]
в каком режиме? эту ошибку я вроде бы устранил

**Comment by drblez** [comment]
Когда состояние ON

```
2016-09-03 15:32:20.479 [INFO ] [b.m.internal.MegaDeviceBinding] - http://192.168.40.40/sec/?pt=1&cmd=get
2016-09-03 15:32:20.488 [INFO ] [b.m.internal.MegaDeviceBinding] - input string->ON/5
2016-09-03 15:32:20.492 [ERROR] [.service.AbstractActiveService] - Error while executing background thread MegaDevice Refresh Service
java.lang.ArrayIndexOutOfBoundsException: 1
    at org.openhab.binding.megadevice.internal.MegaDeviceBinding.ScanPortsScheduler(MegaDeviceBinding.java:264) ~[na:na]
    at org.openhab.binding.megadevice.internal.MegaDeviceBinding.execute(MegaDeviceBinding.java:182) ~[na:na]
    at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
    at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
```

**Comment by Pshatsillo** [comment]
Исправил уже, попробуйте!! :)

**Comment by drblez** [comment]
Я обновил на последнюю версию и ошибки стали возникать только если состояние ON

**Comment by Pshatsillo** [comment]
Да, знаю. Буквально только что заметил и исправил!

**Comment by drblez** [comment]
А JAR выложили? )) Не могу сейчас из сырков собрать ))

**Comment by Pshatsillo** [comment]
момент!! Сейчас будет!:)

**Comment by Pshatsillo** [comment]
https://github.com/Pshatsillo/openHABMegaDevice/releases/download/1.8_java_win_0.1.2.3/org.openhab.binding.megadevice_0.1.2.3.jar

**Comment by drblez** [comment]
Спасибо!
